#!/usr/bin/env python3
"""Wrap the exact native topology in a tscircuit spicemodel subcircuit."""
from pathlib import Path
import json,re
root=Path(__file__).resolve().parents[1]
s=(root/'sim/hv/converter.cir').read_text().split('.control')[0]
lines=s.splitlines()[1:]
lines=[x for x in lines if not x.startswith(('Vbat ','Ven ','.options'))]
# Only replace node token 0, never a parameter value or behavioral constant.
output=[]
node_counts={'R':2,'C':2,'L':2,'D':2,'S':4,'V':2,'B':2,'I':2,'Q':3}
for line in lines:
    if line and line[0].upper() in node_counts and not line.startswith('*'):
        fields=line.split(); n=node_counts[line[0].upper()]
        for i in range(1,n+1):
            if fields[i]=='0': fields[i]='GND'
        line=' '.join(fields)
    # All internal behavioral voltages must refer to the subcircuit return.
    line=re.sub(r'v\((hv|clock|delayed|en|vin|detected|ovp|event|collector)\)',r'v(\1,GND)',line,flags=re.I)
    output.append(line)
sub='.subckt GEIGER_HV battery GND hv sw sense en ttl\n'+'\n'.join(output)+'\n.ends GEIGER_HV\n'
(root/'sim/hv/model.ts').write_text('// Generated by scripts/sync_spice_model.py; edit converter.cir.\nexport const hvModel = '+json.dumps(sub)+'\n')
